language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc scons
script: scons -C firmware build-node-release build-main-release
notifications:
  email: 
    - andreas.dahlberg90@gmail.com