dist: focal
language: c
jdk:
  - oraclejdk11
git:
  depth: false
services:
  - docker
before_install:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t andreasdahlberg/docker-avr docker
  - docker run -v ${TRAVIS_BUILD_DIR}:/home/travis/build -w /home/travis/build -it -d --name build andreasdahlberg/docker-avr bash
script:
  - docker exec build scripts/check_style.py
  - docker exec build scons -C firmware coverage -j2
  - docker exec -w /home/travis/build/firmware build gcovr -k
  - docker exec build build-wrapper-linux-x86-64 --out-dir bw-output scons -C firmware build-main-release build-node-release
  - docker exec build scons -C firmware build-node-release build-main-release eeprom-node-release eeprom-main-release -j2
  - scripts/sonar.py
notifications:
  email:
    - andreas.dahlberg90@gmail.com
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "kP26NzYGlilBstZ2flG2G6SYNhpF5wk6t+IerON4zlnpt19IYm8/mrri8nw8d/bLHbmm+QGwjWAaDVxc8m6/pK1e9FW05JNi7aKt1ZvdEL/Sw6ZKIjYngMMTiRHiGoLpaf33aPYjJYeqhzTzvDBlLoVYaEEBS49R2FHr805Csju1tH8duYdw33yr+uONafizAViO4GR6jFZJpUFHUtZ3c7gmdQIWFp96x2bxqRSvp+QxTG7A8sLxkCTLNhAD2f+DlGSBy94P7BX5KaMTc0We5gghFHKydLWR4bzQRLM+0aFK4JyYJ4DgSz7v3J/gVpz0LjKqwbLqlqhDknx9QBSe2favGfvab5GUNFsJG7GSQNhUNU0uDf3wmWp6nNo77NthDj1WKQ8teMUmW9YRsVJPPaWC2tuzvGl70m7ZhthP9Q4cKExrRm4MvYEMNH27pqibQDRAFR+kL2c7PhIpGO7GNzLrBjsGzMO/EXN28Th2Rmlw2mVDisOhVFM3X+Q1nqDLE7aALIIypvovQnzkUxI4SswDLl5fLnwMk6K6EK+ly3/gamlYBudk65oxqLOSgcbagB80eMrAPuhQ7ySGUh4Mp3xpJjJPWVmEiSq6+Nw45dL3xXO2dg7BMs66qgjgPW/sFvXvVq34wsVC9uJE45ILOsH3OY/C8cjDo1kmOr9MI90="
  file:
    - firmware/build/release/main/main/main_release.hex
    - firmware/build/release/main/main/main_release.eep
    - firmware/build/release/node/node/node_release.hex
    - firmware/build/release/node/node/node_release.eep
  on:
    tags: true
