# -*- coding: utf-8 -*
#
# This file is part of SillyCat Development Tools.
#
# SillyCat Development Tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# SillyCat Development Tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with SillyCat Development Tools.  If not, see <http://www.gnu.org/licenses/>.

__author__ = 'andreas.dahlberg90@gmail.com (Andreas Dahlberg)'

import os

#Directories to compile
DIRECTORIES = [
    'encoder',
    'driver',
    'display',
    'gui',
    'fonts',
    'interface',
    'sensor',
    'nodes',
    'node',
    'board',
    'packethandler',
    '../utility',
    '../common'
]

#Import all exported variables
Import(['*'])


env.Append(CPPPATH=[
    '#src/utility',
    '#src/main',
    '#src/main/board',
    '#src/main/display',
    '#src/main/driver/NHD223',
    '#src/common',
    '#src/common/ADC',
    '#src/common/board',
    '#src/common/timer',
    '#src/common/driver/MCP79510',
    'encoder',
    'driver/PEC11',
    'driver/MCUTemperature',
    'driver/NTC',
    'gui',
    'fonts',
    'interface',
    'nodes',
    'node',
    'packethandler'
])

source = Glob('*.c')
objects = env.Object(source=source)

for subdir in DIRECTORIES:
    objects = objects + env.SConscript('{}/SConscript'.format(subdir), {'env': env, 'mode': mode, 'target': target})


elf_name = '{}_{}.elf'.format(target, mode)
hex_name = '{}_{}.hex'.format(target, mode)
eep_name = '{}_{}.eep'.format(target, mode)

elf = env.Elf(elf_name, objects)
hex = env.Hex(hex_name, elf)
eep = env.EEPROM(eep_name, elf)

Return(['hex', 'elf', 'eep'])
