# -*- coding: utf-8 -*
#
# This file is part of SillyCat Development Tools.
#
# SillyCat Development Tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# SillyCat Development Tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with SillyCat Development Tools.  If not, see <http://www.gnu.org/licenses/>.

import os

Import(['*'])


env.Append(CPPPATH=[
    '#src/main/driver/DS3234',
    '#src/main',
    '#src/common'
    ])

env.Append(LINKFLAGS=[
    '-Wl,--wrap=BCDToDecimal',
    '-Wl,--wrap=DecimalToBCD',
    '-Wl,--wrap=libSPI_WriteByte',
    '-Wl,--wrap=libSPI_ReadByte',
    '-Wl,--wrap=libSPI_Read',
    '-Wl,--wrap=Bit_Get',
])

SOURCE = Glob('*.c')
OBJECTS = env.Object(source=SOURCE)

Return('OBJECTS')
