import os

Import(['*'])

env.Append(CPPPATH=[
    '#src/common/event',
    '#tests/common/event',
])

env.Append(LINKFLAGS=[
    '-Wl,--wrap=Timer_GetMilliseconds',
])

SOURCE = Glob('*.c')
OBJECTS = env.Object(source=SOURCE)

Return('OBJECTS')
