import os

Import(['*'])

env.Append(CPPPATH=[
    '#src/common/com',
    '#src/common/errorhandler',
    '#src/common/transceiver',
    '#tests/common/com',
    '#tests/mocks/'
])

env.Append(LINKFLAGS=[
    '-Wl,--wrap=Transceiver_ReceivePacket',
    '-Wl,--wrap=Transceiver_SendPacket',
    '-Wl,--wrap=RTC_GetCurrentTime',
    '-Wl,--wrap=ErrorHandler_LogError',
])

SOURCE = Glob('*.c')
OBJECTS = env.Object(source=SOURCE)

Return('OBJECTS')
