# -*- coding: utf-8 -*
#
# This file is part of SillyCat Development Tools.
#
# SillyCat Development Tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# SillyCat Development Tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with SillyCat Development Tools.  If not, see <http://www.gnu.org/licenses/>.

import os

Import(['*'])

unit_env.Append(CPPPATH=[
    '#src/main',
    '#src/main/gui',
    '#src/common_library',
    '#tests/mocks'
    ])

unit_env.Append(LINKFLAGS=[
    '-Wl,--wrap=libDisplay_Init',
    '-Wl,--wrap=libDisplay_On',
    '-Wl,--wrap=libDisplay_ClearVRAM',
    '-Wl,--wrap=libTimer_GetMilliseconds',
    '-Wl,--wrap=guiInterface_DrawViewIndicator',
    '-Wl,--wrap=libUI_Update',
    ])

source = [
    'test_Interface.c',
    '#src/common_library/Timer.c',
    ]
objects = unit_env.Object(source=source)

unit_env_cov = unit_env.Clone()
unit_env_cov.Append(CCFLAGS=['--coverage'])
module_under_test = unit_env_cov.Object(source='#src/main/Interface.c')

objects.append(module_under_test)
Return('objects')
