# -*- coding: utf-8 -*
#
# This file is part of SillyCat Development Tools.
#
# SillyCat Development Tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# SillyCat Development Tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with SillyCat Development Tools.  If not, see <http://www.gnu.org/licenses/>.

import os

Import(['*'])

mock_env = env.Clone()
mock_env.Append(CPPPATH=[
    '#src/main',
    '#src/main/gui',
    '#src/main/sensor',
    '#src/main/node',
    '#src/common',
    '#src/common/ADC',
    '#src/common/time',
    '#src/common/timer',
    '#src/common/event',
    '#src/common/errorhandler',
    '#src/common/transceiver',
    '#src/common/driver/UART',
    '#src/common/driver/timer',
    '#src/common/driver/MCP79510',
    '#src/utility/FIFO',
    '#src/utility/Filter'
    ])

source = Glob('*.c')
objects = mock_env.Object(source=source)

Return('objects')
