
Import(['*'])

font_header = env.Font(
    source='font_template.h',
    target='font.h')

font_source = env.Font(
    source='font_template.c',
    target='font.c')

objects = env.Object(source=font_source)
Return('objects')
