import os

Import(['*'])

env.Append(CPPPATH=[
    '#src/common/config',
    '#tests/common/config',
])

env.Append(LINKFLAGS=[
    '-Wl,--wrap=CRC_16',
])

SOURCE = Glob('*.c')
OBJECT = env.Object(source=SOURCE)

Return('OBJECT')
