
import os

Import(['*'])

source = Glob('*.c')

env.Append(CPPPATH=[
    '#src/main/fonts',
    '#src/main/encoder',
    '#src/main/interface',
    '#src/main/driver/NTC',
    '#src/main/nodes',
    ])

objects = env.Object(source=source)

Return('objects')


