# -*- coding: utf-8 -*
#
# This file is part of SillyCat Development Tools.
#
# SillyCat Development Tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# SillyCat Development Tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with SillyCat Development Tools.  If not, see <http://www.gnu.org/licenses/>.

import os

Import(['*'])

env.Append(CPPPATH=[
    '#src/main',
    '#src/main/display',
    '#src/common',
    ])

env.Append(LINKFLAGS=[
    '-Wl,--wrap=driverNHD223_Init',
    '-Wl,--wrap=driverNHD223_SetHorizontalAddressingMode',
    '-Wl,--wrap=driverNHD223_SetColumnAddressRange',
    '-Wl,--wrap=driverNHD223_SetPageAddressRange',
    '-Wl,--wrap=driverNHD223_WriteCommand',
    '-Wl,--wrap=driverNHD223_WriteCommand',
    '-Wl,--wrap=driverNHD223_WriteData',
    '-Wl,--wrap=driverNHD223_ResetDisplay',
    '-Wl,--wrap=driverNHD223_WriteCommand',
    '-Wl,--wrap=driverNHD223_WriteCommand'
    ])

SOURCE = Glob('*.c')
OBJECTS = env.Object(source=SOURCE)

Return('OBJECTS')
