
import os

Import(['*'])

modules = ['ADC', 'timer', 'time', 'com', 'event', 'transceiver']
module_objects = []

source = Glob('*.c')
env.Append(CPPPATH=[
    '#src/common',
    '#src/common/com',
    '#src/common/time',
    '#src/common/event',
    '#src/common/transceiver',
    '#src/utility/FIFO',
    '#src/{}'.format(target)
])

module_objects.append(env.Object(source))

for module in modules:
    sconscript_file = os.path.join(module, 'SConscript')

    module_object = SConscript(sconscript_file, exports = 'env')
    module_objects.append(module_object)

Return('module_objects')
